### ISSUE TITLE
Cant compile lib

### ISSUE THREAD

**Issue by MrEnder0** [pozm/poggers#5]
PS C:\Users\Ender\Current projects\calc-poop> cargo run --release
   Compiling poggers v1.0.3
error[E0599]: no function or associated item named `find_by_pid` found for struct `Process` in the current scope
   --> C:\Users\Ender\.cargo\registry\src\index.crates.io-6f17d22bba15001f\poggers-1.0.3\src\structures\process\mod.rs:100:15
    |
14  | pub struct Process<T = Holding> {
    | ------------------------------- function or associated item `find_by_pid` not found for this struct
...
100 |         Self::find_by_pid(value)
    |               ^^^^^^^^^^^ function or associated item not found in `Process<External>`

error[E0624]: associated function `find_by_name` is private
   --> C:\Users\Ender\.cargo\registry\src\index.crates.io-6f17d22bba15001f\poggers-1.0.3\src\structures\process\mod.rs:107:15
    |
107 |         Self::find_by_name(value)
    |               ^^^^^^^^^^^^ private associated function
    |
   ::: C:\Users\Ender\.cargo\registry\src\index.crates.io-6f17d22bba15001f\poggers-1.0.3\src\structures\process\implement\win32\external.rs:149:5
    |
149 |     fn find_by_name(name: &str) -> Result<Self, ProcessError> {
    |     --------------------------------------------------------- private associated function defined here

Some errors have detailed explanations: E0599, E0624.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `poggers` (lib) due to 2 previous errors

**Comment by char-ptr** [comment]
Hi, could you post the output of `cargo -Vvv`?
Thanks

**Comment by MrEnder0** [comment]
> cargo -Vvv

cargo 1.73.0 (9c4383fb5 2023-08-26)
release: 1.73.0
commit-hash: 9c4383fb55986096b414d98125421ab87b5fd642
commit-date: 2023-08-26
host: x86_64-pc-windows-msvc
libgit2: 1.6.4 (sys:0.17.2 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:Schannel)
os: Windows 10.0.22621 (Windows 11 Core) [64-bit]

**Comment by char-ptr** [comment]
Hi, i made some changes yesterday, could you check if you're able to build it with latest version?

**Comment by MrEnder0** [comment]
Yes it seems to be working perfectly now, thank you.
