### ISSUE TITLE
0x4096 is not a valid page size

### ISSUE THREAD

**Issue by ghassanpl** [pozm/poggers#6]
The code uses `0x4096` as an argument to several memory query/reading functions (on Win32 it's `VirtualQuery`, `ReadProcessMemory`), but `0x4096` is not a page size (or valid multiple/factor) on any system; 4096 is, but not `0x4096` (16534).

This can cause a crash (happened to me) in `Module::scan` when querying returns valid results for the range of pages it asks for (rounding DOWN to nearest page size), and the code decides to copy the **entire** 16534-byte range (with `raw_read`), even though that range may cross inaccessible/invalid pages.

See, for example, https://github.com/pozm/poggers/blob/39850285c4c66efe0158a50a69a359fcbf3391da/src/structures/modules/implement.rs#L24

**Comment by char-ptr** [comment]
Good spot! 

I'll try to get around to fixing this and making a release to fix this tomorrow.

Thanks :)

**Comment by char-ptr** [comment]
This should now be fixed with release 1.1.7.

Thanks again
